version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bio-network

  oxigraph:
    image: ghcr.io/oxigraph/oxigraph
    command: serve --location /data --bind [::]:7878
    ports:
      - "7878:7878"
    volumes:
      - ./oxigraph:/data
    networks:
      - bio-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bio-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/postgres
      GCP_CREDENTIALS_PATH: /app/config/otdkg-383119-87a0bc5dc94c.json
    volumes:
      - ./config/otdkg-383119-87a0bc5dc94c.json:/app/config/otdkg-383119-87a0bc5dc94c.json
    depends_on:
      - postgres
      - oxigraph
    networks:
      - bio-network

volumes:
  postgres_data:
  oxigraph:

networks:
  bio-network:
    driver: bridge
